### PR TITLE
Decrease Page-load Times

### PR DESCRIPTION
**Pull request by JackStouffer**
Changes are described in the commit titles

Still investigating the multiple jQuery issue.

@mdparker @wilzbach

### CODE REVIEW

**Comment by mdparker** [comment]
Hmm. The merge was successful but the PR didn't close automatically.

**Comment by wilzbach** [comment]
> Hmm. The merge was successful but the PR didn't close automatically.

Maybe due to some rebasing? Github only likes "clear" merges with a commit ...

**Comment by CyberShadow** [comment]
Was the merge done from the command line, or from the GitHub web UI?

**Comment by mdparker** [comment]
I used the merge button on the web page. The page got stuck waiting for a
reload and never refreshed.

**Pull request closed without merging**
