### PR TITLE
change copyright to D Language Foundation

### PR DESCRIPTION
**Pull request by wilzbach**
@JackStouffer I hope I found the right spot to change that.
Do we even need the "All rights reserved" btw?

### CODE REVIEW

**Comment by JackStouffer** [comment]
Sorry I forgot about this.

I think these posts should be licensed under a CC license rather than be owned by the foundation, as that makes spreading the ideas in the text much less legally ambiguous. That's up to @mdparker though.

**Comment by mdparker** [comment]
Oh, I completely missed this.

I only chose the current copyright line as it is what is used on the forums. I would be happy with a CC license (though, that doesn't preclude a copyright claim, does it?), but I think that's something that @WalterBright should have the final say on. I also think it shouldn't be considered solely in regards to the blog, but in terms of the entire web site.

**Comment by mdparker** [comment]
Walter says it should be The D Foundation.

**Comment by mdparker** [comment]
@wilzbach I think the link should be 'https'. If you can update that for me, I'll merge it.

**Comment by wilzbach** [comment]
> Walter says it should be The D Foundation.

:)

> @wilzbach I think the link should be 'https'. If you can update that for me, I'll merge it.

Done.

**Pull request merged**
